# Site
title: 'material.fail'
subtitle: ''

# URL
url: https://materialfail-org.github.io
baseurl: ''
include: ['_pages']

collections:
  pages:
    output: true
    permalink: /:name


# Build settings
markdown: kramdown
port: 9696
future: false

# Defaults
defaults:
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "home"

# Data
social:
  facebook: "https://www.facebook.com/user"
  instagram: "https://www.instagram.com/user"
  github: "https://github.com/materialfail-org"
  twitter: "https://twitter.com/user"
  youtube: ""
  vimeo: ""
  soundcloud: ""
  tumblr: ""
  pinterest: ""
  envelope-o: "mailto:material@material.fail"

# prose.io
prose:
  media: 'media/images'
  ignore:
    - CNAME
    - .gitignore
    - _config.yml
    - _includes
    - _layouts
    - _pages/404.md
    - _sass
    - css
    - js
    - media/favicons
    - media/images/covers
    - python
  metadata:
    _pages:
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "nome da editora"
          placeholder: "Colocar Aqui o Nome Da Editora"
      - name: "site"
        field:
          element: "text"
          label: "site da editora"
          placeholder: "https://editora.com"
      - name: "email"
        field:
          element: "text"
          label: "email de contato da editora"
          placeholder: "contato@editora.com"
      - name: "about-en"
        field:
          element: "textarea"
          label: "descrição da editora em INGLÊS"
          placeholder: "bla bla bla"
      - name: "about-es"
        field:
          element: "textarea"
          label: "descrição da editora em ESPANHOL"
          placeholder: "bla bla bla"
      - name: "about-pt"
        field:
          element: "textarea"
          label: "descrição da editora em PORTUGUÊS"
          placeholder: "bla bla bla"
